// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdhjyhettxoackdbrajb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkaGp5aGV0dHhvYWNrZGJyYWpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MTkwOTEsImV4cCI6MjA2MjM5NTA5MX0.984d7Fqr1u-BEIrQfSopA99jMwRHAfa3byOLndvMYN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);